swagger: '2.0'
x-api-id: name
info:
  version: 1.0.0
  title: name
  license:
    name: ISC
    url: 'http://localhost:3000'
paths:
  '/getUserRaces/{userId}':
    get:
      description: return user with his races
      parameters:
        - in: path
          name: userId
          required: true
          description: The user id
          type: string
          default: hi
      responses:
        '200':
          description: OK
        '400':
          description: Bad request. User ID must be an string and bigger than 0.
        '401':
          description: Authorization information is missing or invalid.
        '404':
          description: A user with the specified ID was not found.
  '/getUserLeagues/{userId}':
    get:
      description: return user with his league
      parameters:
        - in: path
          name: userId
          required: true
          description: The user id
          type: string
          default: hi
      responses:
        '200':
          description: OK
        '400':
          description: Bad request. User ID must be an string and bigger than 0.
        '401':
          description: Authorization information is missing or invalid.
        '404':
          description: A user with the specified ID was not found.
  '/getSeasonRaces/{season}':
    get:
      description: return user with his league
      parameters:
        - in: path
          name: season
          required: true
          description: Name of season
          type: string
          default: hi
      responses:
        '200':
          description: OK
        '400':
          description: Bad request. Season must be an string and bigger than 0.
        '401':
          description: Authorization information is missing or invalid.
        '404':
          description: Races with this season was not found.
  '/{table}/{tableId}':
    get:
      description: 'Returns a specific table, that id matches the tableId'
      parameters:
        - in: path
          name: tableId
          required: true
          description: The table id
          type: string
          default: hi
        - in: path
          name: table
          required: true
          description: The table value
          type: string
          default: hi
      responses:
        '200':
          description: OK
        '400':
          description: Bad request. User ID must be an string and bigger than 0.
        '401':
          description: Authorization information is missing or invalid.
        '404':
          description: A user with the specified ID was not found.
    put:
      description: 'Update a specific table, that id matches the tableId, and return it'
      parameters:
        - in: path
          name: tableId
          required: true
          description: The table id
          type: string
          default: hi
        - in: path
          name: table
          required: true
          description: The table value
          type: string
          default: hi
      responses:
        '200':
          description: OK
        '400':
          description: Bad request. User ID must be an string and bigger than 0.
        '401':
          description: Authorization information is missing or invalid.
        '404':
          description: Instance by given name or id was not found.
    delete:
      description: 'Delete a specific table, that id matches the tableId'
      parameters:
        - in: path
          name: tableId
          required: true
          description: The table id
          type: string
          default: hi
        - in: path
          name: table
          required: true
          description: The table value
          type: string
          default: hi
      responses:
        '200':
          description: OK
        '400':
          description: Bad request. User ID must be an string and bigger than 0.
        '401':
          description: Authorization information is missing or invalid.
        '404':
          description: A user with the specified ID was not found.
  '/{table}':
    post:
      description: Create a new table instance
      parameters:
        - in: path
          name: table
          required: true
          description: The table value
          type: string
          default: hi
      responses:
        '200':
          description: OK
        '400':
          description: Bad request. User ID must be an string and bigger than 0.
        '401':
          description: Authorization information is missing or invalid.
        '404':
          description: Instance by given name was not found.
